services:
  app:
    build:
      context: .
      args:
        REACT_APP_GITHUB_API_KEY: ${REACT_APP_GITHUB_API_KEY}
    ports:
      - "3000:80"
    environment:
      - REACT_APP_GITHUB_API_KEY=${REACT_APP_GITHUB_API_KEY}
    env_file:
      - .env
    restart: always
